name: snake_env
channels:
  - omnia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _r-mutex
  - binutils_impl_linux-64
  - binutils_linux-64
  - blas
  - bwidget
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - curl
  - cycler
  - fontconfig
  - freetype
  - fribidi
  - gcc_impl_linux-64
  - gcc_linux-64
  - gettext
  - gfortran_impl_linux-64
  - gfortran_linux-64
  - glib
  - graphite2
  - gsl
  - gxx_impl_linux-64
  - gxx_linux-64
  - harfbuzz
  - icu
  - joblib
  - jpeg
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - libblas
  - libcblas
  - libcurl
  - libedit
  - libev
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libiconv
  - liblapack
  - libnghttp2
  - libopenblas
  - libpng
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libxml2
  - lz4-c
  - make
  - matplotlib
  - matplotlib-base
  - ncurses
  - numpy
  - olefile
  - openssl
  - pango
  - pcre
  - pcre2
  - pillow
  - pip
  - pixman
  - pthread-stubs
  - pyparsing
  - python
  - python-dateutil
  - python_abi
  - r-base
  - r-baseline
  - r-limsolve
  - r-lpsolve
  - r-mass
  - r-quadprog
  - r-sparsem
  - readline
  - scikit-learn
  - scipy
  - sed
  - setuptools
  - six
  - sqlite
  - termcolor
  - threadpoolctl
  - tk
  - tktable
  - tornado
  - wheel
  - wrapt
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - zlib
  - zstd
  - pip:
    - pyyaml

