####################################################################################################################################
# Dataset Creation
# Optional: you can download the data instead
####################################################################################################################################
create_dataset:
  seed: 0
  variable_scope: 0
  model_dir: TODO # path to model files
  # learning
  num_timesteps: 1500000
  num_train: 1000000
  save_frequency:  5000
  episode_length: 1000
  # subtrajectory creation
  subtrajectry_length: 50
  subtrajectories_per_episode: 100
  max_num_subtrajectories: 20000
  # saving
  data_dir: TODO # saving path for subtrajectories.npy
####################################################################################################################################
# Reward Learning
####################################################################################################################################
train:
  seed: 0
  # data
  data_dir: TODO # path to subtrajectories
  subtrajectry_length: 50
  subtrajectories_per_episode: 100
  max_num_subtrajectories: 20000
  episode_length: 1000
  # reward learning
  input_dim: 27
  split_ratio: 0.9
  save_dir: TODO # save path for synthetic reward function and policies learnt on top of it
  epochs: 20
  lr: 0.00005
  # ranking
  ranking_method: TODO # chosen ranking method
  margin: 200000
  # policy optimization
  run_rl: true
  num_agents: 1
  num_timesteps: 1000000
  save_sequency: 100000
  ctrl_coeff: 0.0
  # docu
  tensorboard_dir: TODO # path for tensorboard logs
####################################################################################################################################
# Experiments
####################################################################################################################################
ranking_quality:
  seed: 0
  data_path: TODO
  num_samples: 200
  triplet_path: TODO
  pair_path: TODO

rl_on_top:
  seed: 0
  runs_per_model: 1
  paths_with_var_scops:
    - model0:
        - 1
        - TODO
    - model1:
        - 2
        - TODO
    - model2:
        - 3
        - TODO
    - model3:
        - 4
        - TODO
    - model4:
        - 5
        - TODO

extrapolation:
  seed: 0
  num_samples: 100
  train_path: TODO
  extrapolation_path: TODO
  net_path: TODO

correlation:
  seed: 0
  pair_net_path: TODO
  triplet_net_path: TODO
  data_path: TODO

####################################################################################################################################
# Visualization
####################################################################################################################################
visualize:
  seed: 0
  variable_scope: 1
  model_index: 0
  model_dir: TODO





